name: build-u-boot

env:
  IMAGE_BASE: onion/u-boot-builder
  S3_BUCKET: mybucket

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compute variables
      id: vars
      run: |
        date=$(date +'%Y%m%d')
        echo "DATE=\"${date}\"" >> "$GITHUB_ENV"
        github_sha_hash=${{ github.sha }}
        github_sha_short="${github_sha_hash:0:7}"
        echo "GITHUB_SHA_SHORT=${github_sha_short}" >> "$GITHUB_ENV"
        echo "IMAGE_TAG_LATEST=${{env.IMAGE_BASE}}:latest" >> "$GITHUB_ENV"
        echo "IMAGE_TAG_FULL=\"${{env.IMAGE_BASE}}:${date}-${github_sha_short}\"" >> "$GITHUB_ENV"

    - name: Prepare u-boot tree
      run: |
        bash build.sh setup_tree
        cat u-boot/Makefile | head -n 8
    
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build multiarch image and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            ${{ env.IMAGE_TAG_LATEST }}
            ${{ env.IMAGE_TAG_FULL }}
        cache-from: type=registry,ref=onion/u-boot-builder:buildcache
        cache-to:   type=registry,ref=onion/u-boot-builder:buildcache,mode=max
    
    - name: Export image tag
      id: meta
      run: echo "tag=onion/u-boot-builder:${{ env.DATE }}"
    outputs:
      image_tag: ${{ env.IMAGE_TAG_FULL }}
  
  build-u-boot:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: sanity check
      run: |
        echo "Image tag: ${{ needs.build-image.outputs.image_tag }}"
        echo "S3 bucket: ${{ env.S3_BUCKET }}"

    - name: Pull image
      run: |
        docker pull ${{ needs.build-image.outputs.image_tag }}

    - name: Build u-boot in container
      run: |
        mkdir -p out
        docker run -rm \
          -v $PWD/out:/u-boot/output \
          ${{ needs.build-image.outputs.image_tag }}
          /bin/bash -c "bash build.sh build_uboot"
        ll out